# Generated by Django 5.0.3 on 2024-04-15 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=255)),
                ('like_users', models.TextField(default='', null=True)),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PostComments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('times_of_use', models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'Hashtag',
                'ordering': ['-times_of_use'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('view_mode', models.IntegerField(choices=[(0, 'Public'), (1, 'Follower'), (2, 'Fan'), (3, 'Fiend'), (4, 'Private')], default=0)),
                ('chat_mode', models.IntegerField(choices=[(0, 'Public'), (1, 'Follower'), (2, 'Fan'), (3, 'Fiend'), (4, 'Private')], default=0)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('hashtags', models.TextField(default='')),
                ('like_users', models.TextField(blank=True, default='', null=True)),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('image_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Post_Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepComment',
            fields=[
                ('rep_cmt_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=255)),
                ('like_users', models.TextField(default='', null=True)),
                ('like_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PostRepComment',
                'ordering': ['-created_at'],
            },
        ),
    ]
