# Generated by Django 5.0.3 on 2024-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='repcomment',
            name='like_users',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
